version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  # Expose Next.js port
    volumes:
      - ./frontend:/app  # Mount the entire frontend directory
      - /app/node_modules  # Isolate node_modules between host and container
    working_dir: /app  # Set the working directory inside the container
    environment:
      - NODE_ENV=development
    command: "npm run dev"  # Start Next.js in development mode

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5433:5432"  # Forward PostgreSQL port to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database
      - ./backend/data:/docker-entrypoint-initdb.d  # Copy initial data
    environment:
      POSTGRES_USER: oki_user
      POSTGRES_PASSWORD: team_oki
      POSTGRES_DB: pbl_ticket

volumes:
  postgres_data: {}
