export const translations = {
  ja: {
    sectionTitle: 'ご利用になる区間・日時・人数を',
    sectionSubtitle: 'お選びください',
    timeNote: '所要時間が短い組み合わせを優先してご案内します。',
    departureStation: '出発駅',
    arrivalStation: '到着駅',
    swapStations: '↑入れ替え↓',
    departureStationPlaceholder: '出発駅を入力',
    arrivalStationPlaceholder: '到着駅を入力',
    selectDepartureStation: '出発駅を選択',
    selectArrivalStation: '到着駅を選択',
    change: '変 更',
    input: '入 力',
    dateTime: '利用日時',
    today: '(本日)',
    confirm: '確定',
    departure: '出発',
    arrival: '到着',
    passengers: '人数',
    adults: '大人',
    children: 'こども',
    person: '人',
    conditions: '条件',
    shinkansen: '新幹線を',
    use: '利用する',
    viaStation: '経由駅',
    noDesignation: '指定なし',
    cancel: '取消',
    back: '前画面に戻る',
    monochrome: '白黒表示',
    confirmation: 'よろしければ',
    confirmButton: '確 認',
    cancelConfirmation: '入力内容を取り消しますか？',
    no: 'いいえ',
    yes: 'はい',
    selectDepartureStationModalTitle: '出発駅を選択',
    stationNamePlaceholder: '駅名を入力',
    cancelButton: 'キャンセル',
    confirmModalButton: '確定',
    inputContent: 'ここまでの入力内容',
    fare: '運賃',
    calculating: '運賃を計算中です...',
    fareNotAvailable: '運賃が取得できませんでした。'
  },
  en: {
    sectionTitle: 'Please select section, date, time, and number of passengers',
    sectionSubtitle: '',
    timeNote: 'We will prioritize combinations with shorter travel times.',
    departureStation: 'Departure Station',
    arrivalStation: 'Arrival Station',
    swapStations: '↑ Swap ↓',
    departureStationPlaceholder: 'Enter departure station',
    arrivalStationPlaceholder: 'Enter arrival station',
    selectDepartureStation: 'Select Departure Station',
    selectArrivalStation: 'Select Arrival Station',
    change: 'Change',
    input: 'Input',
    dateTime: 'Date and Time',
    today: '(Today)',
    confirm: 'Confirm',
    departure: 'Departure',
    arrival: 'Arrival',
    passengers: 'Passengers',
    adults: 'Adults',
    children: 'Children',
    person: '',
    conditions: 'Conditions',
    shinkansen: 'Use',
    use: 'Shinkansen',
    viaStation: 'Via Station',
    noDesignation: 'No Designation',
    cancel: 'Cancel',
    back: 'Back to Previous Screen',
    monochrome: 'Monochrome Display',
    confirmation: 'If you are sure',
    confirmButton: 'Confirm',
    cancelConfirmation: 'Are you sure you want to cancel the input?',
    no: 'No',
    yes: 'Yes',
    selectDepartureStationModalTitle: 'Select Departure Station',
    stationNamePlaceholder: 'Enter station name',
    cancelButton: 'Cancel',
    confirmModalButton: 'Confirm',
    inputContent: 'Input Content',
    fare: 'Fare',
    calculating: 'Calculating fare...',
    fareNotAvailable: 'Fare not available.'
  },
  zh: {
    sectionTitle: '请选择区间、日期、时间和乘客人数',
    sectionSubtitle: '',
    timeNote: '我们将优先考虑行程时间较短的组合。',
    departureStation: '出发站',
    arrivalStation: '到达站',
    swapStations: '↑ 交换 ↓',
    departureStationPlaceholder: '请输入出发站',
    arrivalStationPlaceholder: '请输入到达站',
    selectDepartureStation: '选择出发站',
    selectArrivalStation: '选择到达站',
    change: '更改',
    input: '输入',
    dateTime: '日期和时间',
    today: '(今天)',
    confirm: '确认',
    departure: '出发',
    arrival: '到达',
    passengers: '乘客',
    adults: '成人',
    children: '儿童',
    person: '',
    conditions: '条件',
    shinkansen: '使用',
    use: '新干线',
    viaStation: '途经站',
    noDesignation: '无指定',
    cancel: '取消',
    back: '返回上一屏幕',
    monochrome: '黑白显示',
    confirmation: '如果您确定',
    confirmButton: '确认',
    cancelConfirmation: '您确定要取消输入吗？',
    no: '否',
    yes: '是',
    selectDepartureStationModalTitle: '选择出发站',
    stationNamePlaceholder: '请输入车站名称',
    cancelButton: '取消',
    confirmModalButton: '确认',
    inputContent: '输入内容',
    fare: '运费',
    calculating: '计算运费...',
    fareNotAvailable: '运费无法获取。'
  },
  ko: {
    sectionTitle: '구간, 날짜, 시간 및 승객 수를 선택하십시오',
    sectionSubtitle: '',
    timeNote: '소요 시간이 짧은 조합을 우선적으로 안내합니다.',
    departureStation: '출발역',
    arrivalStation: '도착역',
    swapStations: '↑ 교체 ↓',
    departureStationPlaceholder: '출발역 입력',
    arrivalStationPlaceholder: '도착역 입력',
    selectDepartureStation: '출발역 선택',
    selectArrivalStation: '도착역 선택',
    change: '변경',
    input: '입력',
    dateTime: '날짜 및 시간',
    today: '(오늘)',
    confirm: '확인',
    departure: '출발',
    arrival: '도착',
    passengers: '인원',
    adults: '성인',
    children: '어린이',
    person: '',
    conditions: '조건',
    shinkansen: '사용',
    use: '신칸센',
    viaStation: '경유역',
    noDesignation: '지정 없음',
    cancel: '취소',
    back: '이전 화면으로 돌아가기',
    monochrome: '흑백 표시',
    confirmation: '확실하다면',
    confirmButton: '확인',
    cancelConfirmation: '입력을 취소하시겠습니까?',
    no: '아니요',
    yes: '예',
    selectDepartureStationModalTitle: '출발역 선택',
    stationNamePlaceholder: '역 이름 입력',
    cancelButton: '취소',
    confirmModalButton: '확인',
    inputContent: '입력 내용',
    fare: '요금',
    calculating: '요금을 계산 중입니다...',
    fareNotAvailable: '요금을 얻을 수 없습니다.'
  },
};

export const dayOfWeek = {
  ja: ['日', '月', '火', '水', '木', '金', '土'],
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  zh: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  ko: ['일', '월', '화', '수', '목', '금', '토'],
};

export const formatMonthDate = {
  ja: (month: number, day: number) => `${month}月${day.toString().padStart(2, '0')}日`,
  en: (month: number, day: number) => `${month.toString().padStart(2, '0')}/${day.toString().padStart(2, '0')}`,
  zh: (month: number, day: number) => `${month}月${day.toString().padStart(2, '0')}日`,
  ko: (month: number, day: number) => `${month}월 ${day.toString().padStart(2, '0')}일`,
};

export const defaultStationNames = {
  en: 'Takasaki',
  ja: '高崎',
  zh: '高崎',
  ko: '다카사키'
};